# This allows aliases to work with sudo, see also: https://askubuntu.com/a/22043/182607
alias sudo='sudo '

# Change some stuff specific to the Emacs shell
if [ -n "$INSIDE_EMACS" ]; then
    export PAGER=/bin/cat
    export MANPAGER=/bin/cat
    export GIT_PAGER=/bin/cat
    export SYSTEMD_PAGER=/bin/cat
    alias apt="apt -o Dpkg::Progress-Fancy=0"
    #export EDITOR=emacsclient
    #alias git="git --no-pager"
fi

alias dpkg-list='dpkg-query -W -f '\''${db:Status-Abbrev} ${Package}\n'\'
