;;; rethink.el

;; Some common settings for Rethink Robotics Lisp hackers. Right now this file just sets
;; some indentation.

(provide 'rethink)

(defun set-rethink-lisp-indent ()
  (put 'case 'lisp-indent-function 1)
  (put 'until 'lisp-indent-function 1)
  (put 'multiple-value-bind 'lisp-indent-function 2)
  (put 'dohash 'lisp-indent-function 1)
  (put 'with-no-suspension 'lisp-indent-function 0)
  (put 'with-open-file 'lisp-indent-function 1)
  (put 'make-robust-controller-interface 'lisp-indent-function 1)
  (put 'macrolet 'lisp-indent-function 1)
  (put 'if-brain-def 'lisp-indent-function 1)
  (put 'if-brain-def-and 'lisp-indent-function 1)
  (put 'if-brain-not-def 'lisp-indent-function 1)
  (put 'ifdef 'lisp-indent-function 1)
  (put 'ract-perf-behave 'lisp-indent-function 2)
  (put 'do-attrs 'lisp-indent-function 1)
  (put 'catch-errors 'lisp-indent-function 1)
  (put 'catch-errors-if 'lisp-indent-function 2)
  (put 'with-location-reserved 'lisp-indent-function 1)
  (put 'with-action-catch 'lisp-indent-function 1)
  (put 'with-lock 'lisp-indent-function 1)
  (put 'with-lock-maybe 'lisp-indent-function 1)
  (put 'with-read-lock 'lisp-indent-function 1)
  (put 'with-read-lock-maybe 'lisp-indent-function 1)
  (put 'with-write-lock 'lisp-indent-function 1)
  (put 'with-write-lock-maybe 'lisp-indent-function 1)
  (put 'with-rc-req 'lisp-indent-function 1)
  (put 'with-context 'lisp-indent-function 1)
  (put 'with-tuning-table-keys 'lisp-indent-function 1)
  (put 'with-contact-control 'lisp-indent-function 1)
  (put 'do-json-vector 'lisp-indent-function 1)
  (put 'do-json-object 'lisp-indent-function 1)
  (put 'do-json-set 'lisp-indent-function 1))
